version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spendsmart_db
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    volumes:
      - redis:/data

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    restart: unless-stopped
    command: server /home/shared --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080

  nodejs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spendsmart_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - JWT_SECRET=mySuperSecretJwtKey
    depends_on:
      - postgres

volumes:
  postgres-data:
  minio:
  redis: